name: Go CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20.x
      
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: '6.0'

      - name: Run tests
        run: go test ./...

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: amidead/bookshelf-api:latest
          dockerfile: Dockerfile

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH }}
          port: ${{ secrets.SERVER_PORT }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            docker pull amidead/bookshelf-api:latest
            docker stop my-app || true
            docker rm my-app || true
            docker run -d --name my-app -p 4040:4040 -e “mongodb://localhost:27017” amidead/bookshelf-api:latest