name: Go CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20.x
      
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: '6.0'

      - name: Run tests
        run: go test

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: amidead/bookshelf-api
          dockerfile: Dockerfile

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            docker stop my-app || true
            docker rm my-app || true
            docker run -d --name my-app -p 4040:4040 -p 27017:27017 -e “mongodb://localhost:27017” amidead/bookshelf-api