name: Test

on:
  push:
    branches:
      - main

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Install go
      uses: actions/setup-go@v2
      with:
        go-version: 1.20.x
      
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.8.0
      with:
        mongodb-version: '6.0'

    - uses: actions/checkout@v3

    - name: Test
      run: go test ./...